Integrating network and http-server for runc in benchmark

diff --git a/resources/runc/build b/resources/runc/build
--- a/resources/runc/build
+++ b/resources/runc/build
@@ -9,7 +9,7 @@ build() {
 	# Checking original image availability
 	docker images | grep ${image} > /dev/null
 	if [ $(echo $?) -eq 1 ]; then
-		echo "ERROR: ${image}: not found in docker images"
+		>&2 echo "ERROR: ${image}: not found in docker images"
 		return 1
 	fi
 	
@@ -25,24 +25,26 @@ build() {
 	local base=$(docker run -d ${image}:latest)
 	docker export ${base} | tar -C ${ro_rootfs} -xv > /dev/null
 	if [ $(echo $?) -eq 1 ]; then
-		echo "ERROR: ${image}: While exporting image from docker"
+		>&2 echo "ERROR: ${image}: While exporting image from docker"
 		return 1
   else
     echo "INFO: ${image}: Image successfully imported from docker"
   fi
+  docker stop ${base} > /dev/null
   docker rm ${base} > /dev/null
 	
 	# Moving editable folder in editable rootfs
-	for d in home media mnt opt root srv sys tmp; do
-	  mv ${ro_rootfs}${d} ${rootfs}${d}
-	done
+	while IFS= read -r line; do
+	    mv ${ro_rootfs}${line} ${rootfs}${line}
+	done < ${DIR}/${image}/wr.list
+	
 	rm -rf ${ro_rootfs}proc
 	mkdir ${rootfs}proc
 	
 	# Creating links to no yet mounted read-only folders
-	for d in bin dev etc lib run sbin usr var; do
-	  ln -s mnt/${d} ${rootfs}/${d}
-	done
+	while IFS= read -r line; do
+	  ln -s mnt/${line} ${rootfs}/${line}
+	done < ${DIR}/${image}/ro.list
 }
 
 for arg in "$@"
diff --git a/resources/runc/clean b/resources/runc/clean
--- a/resources/runc/clean
+++ b/resources/runc/clean
@@ -2,7 +2,7 @@
 
 DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit ; pwd -P )
 LOG_FILE="${DIR}/build.log"
-POOL="~/.runc"
+POOL="${HOME}/.local/share/runc/pool"
 
 # Check if container exists
 CONTAINER=$1
@@ -14,7 +14,7 @@ for i in $(cd ${POOL} && ls -d */ | cut -f1 -d'/'); do
 done
 
 if [ ${VALID} -eq 1 ]; then
-	echo "The container ${CONTAINER} doesn't exist"
+	>&2 echo "ERROR: ${CONTAINER}: This container doesn't exist"
 	exit 1
 fi
 
diff --git a/resources/runc/create b/resources/runc/create
--- a/resources/runc/create
+++ b/resources/runc/create
@@ -2,7 +2,7 @@
 
 DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit ; pwd -P )
 LOG_FILE="${DIR}/build.log"
-POOL="~/.runc"
+POOL="${HOME}/.local/share/runc/pool"
 
 # Check if the image exists
 IMAGE=$1
@@ -14,7 +14,7 @@ for i in $(cd ${DIR} && ls -d */ | cut -f1 -d'/'); do
 done
 
 if [ ${VALID} -eq 1 ]; then
-	echo "The image ${IMAGE} doesn't exist"
+	>&2 echo "ERROR: ${IMAGE}: This image doesn't exist"
 	exit 1
 fi
 
@@ -31,7 +31,7 @@ cp ${DIR}/${IMAGE}/config.json ${FOLDER}/config.json
 bindfs -p 555 --no-allow-other ${DIR}/${IMAGE}/ro-rootfs ${FOLDER}/rootfs/mnt
 if [ $(echo $?) -eq 1 ]; then
 	rm -rf ${FOLDER}
-	echo "The container couldn't be created"
+	>&2 echo "ERROR: ${CONTAINER}: This container couldn't be created"
 	exit 1
 fi
 
